name: ModSimPy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - pint
  - sympy
  - lxml>=4.3
  - html5lib>=1.0
  - beautifulsoup4>=4.7
  - pytables>=3.5
  - pip
  - pip:
    - modsimpy
  
  




